### ISSUE TITLE
Screwed up my drivers

### ISSUE THREAD

**Issue by seb-thomas** [ubuntuxtreme/Nvidia-installer#4]
After several attempts at running this (it invariably errored), I left it to install drivers, and when it screwed up everything, and ran it again it had the nerve to tell me I'd messed up my drivers. 
Cheef

**Comment by drpaneas** [comment]
Shit happens. If you want me to help you, give some information:
1) Your GPU model
2) Ubuntu version
3) Driver you had before using my script
4) Driver you have after using my script

**Comment by seb-thomas** [comment]
Oh, no I don't want help, I just meant the message was inaccurate!
